# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/keiichi/Git/fcitx-skk-plus

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/keiichi/Git/fcitx-skk-plus

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/keiichi/Git/fcitx-skk-plus/CMakeFiles /home/keiichi/Git/fcitx-skk-plus/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/keiichi/Git/fcitx-skk-plus/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named fcitx-addon-translation-handler-1

# Build rule for target.
fcitx-addon-translation-handler-1: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fcitx-addon-translation-handler-1
.PHONY : fcitx-addon-translation-handler-1

# fast build rule for target.
fcitx-addon-translation-handler-1/fast:
	$(MAKE) -f CMakeFiles/fcitx-addon-translation-handler-1.dir/build.make CMakeFiles/fcitx-addon-translation-handler-1.dir/build
.PHONY : fcitx-addon-translation-handler-1/fast

#=============================================================================
# Target rules for targets named fcitx-addon-translation-handler-10

# Build rule for target.
fcitx-addon-translation-handler-10: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fcitx-addon-translation-handler-10
.PHONY : fcitx-addon-translation-handler-10

# fast build rule for target.
fcitx-addon-translation-handler-10/fast:
	$(MAKE) -f CMakeFiles/fcitx-addon-translation-handler-10.dir/build.make CMakeFiles/fcitx-addon-translation-handler-10.dir/build
.PHONY : fcitx-addon-translation-handler-10/fast

#=============================================================================
# Target rules for targets named fcitx-addon-translation-handler-11

# Build rule for target.
fcitx-addon-translation-handler-11: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fcitx-addon-translation-handler-11
.PHONY : fcitx-addon-translation-handler-11

# fast build rule for target.
fcitx-addon-translation-handler-11/fast:
	$(MAKE) -f CMakeFiles/fcitx-addon-translation-handler-11.dir/build.make CMakeFiles/fcitx-addon-translation-handler-11.dir/build
.PHONY : fcitx-addon-translation-handler-11/fast

#=============================================================================
# Target rules for targets named fcitx-addon-translation-handler-12

# Build rule for target.
fcitx-addon-translation-handler-12: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fcitx-addon-translation-handler-12
.PHONY : fcitx-addon-translation-handler-12

# fast build rule for target.
fcitx-addon-translation-handler-12/fast:
	$(MAKE) -f CMakeFiles/fcitx-addon-translation-handler-12.dir/build.make CMakeFiles/fcitx-addon-translation-handler-12.dir/build
.PHONY : fcitx-addon-translation-handler-12/fast

#=============================================================================
# Target rules for targets named fcitx-addon-translation-handler-2

# Build rule for target.
fcitx-addon-translation-handler-2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fcitx-addon-translation-handler-2
.PHONY : fcitx-addon-translation-handler-2

# fast build rule for target.
fcitx-addon-translation-handler-2/fast:
	$(MAKE) -f CMakeFiles/fcitx-addon-translation-handler-2.dir/build.make CMakeFiles/fcitx-addon-translation-handler-2.dir/build
.PHONY : fcitx-addon-translation-handler-2/fast

#=============================================================================
# Target rules for targets named fcitx-addon-translation-handler-3

# Build rule for target.
fcitx-addon-translation-handler-3: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fcitx-addon-translation-handler-3
.PHONY : fcitx-addon-translation-handler-3

# fast build rule for target.
fcitx-addon-translation-handler-3/fast:
	$(MAKE) -f CMakeFiles/fcitx-addon-translation-handler-3.dir/build.make CMakeFiles/fcitx-addon-translation-handler-3.dir/build
.PHONY : fcitx-addon-translation-handler-3/fast

#=============================================================================
# Target rules for targets named fcitx-addon-translation-handler-4

# Build rule for target.
fcitx-addon-translation-handler-4: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fcitx-addon-translation-handler-4
.PHONY : fcitx-addon-translation-handler-4

# fast build rule for target.
fcitx-addon-translation-handler-4/fast:
	$(MAKE) -f CMakeFiles/fcitx-addon-translation-handler-4.dir/build.make CMakeFiles/fcitx-addon-translation-handler-4.dir/build
.PHONY : fcitx-addon-translation-handler-4/fast

#=============================================================================
# Target rules for targets named fcitx-addon-translation-handler-5

# Build rule for target.
fcitx-addon-translation-handler-5: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fcitx-addon-translation-handler-5
.PHONY : fcitx-addon-translation-handler-5

# fast build rule for target.
fcitx-addon-translation-handler-5/fast:
	$(MAKE) -f CMakeFiles/fcitx-addon-translation-handler-5.dir/build.make CMakeFiles/fcitx-addon-translation-handler-5.dir/build
.PHONY : fcitx-addon-translation-handler-5/fast

#=============================================================================
# Target rules for targets named fcitx-addon-translation-handler-6

# Build rule for target.
fcitx-addon-translation-handler-6: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fcitx-addon-translation-handler-6
.PHONY : fcitx-addon-translation-handler-6

# fast build rule for target.
fcitx-addon-translation-handler-6/fast:
	$(MAKE) -f CMakeFiles/fcitx-addon-translation-handler-6.dir/build.make CMakeFiles/fcitx-addon-translation-handler-6.dir/build
.PHONY : fcitx-addon-translation-handler-6/fast

#=============================================================================
# Target rules for targets named fcitx-addon-translation-handler-7

# Build rule for target.
fcitx-addon-translation-handler-7: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fcitx-addon-translation-handler-7
.PHONY : fcitx-addon-translation-handler-7

# fast build rule for target.
fcitx-addon-translation-handler-7/fast:
	$(MAKE) -f CMakeFiles/fcitx-addon-translation-handler-7.dir/build.make CMakeFiles/fcitx-addon-translation-handler-7.dir/build
.PHONY : fcitx-addon-translation-handler-7/fast

#=============================================================================
# Target rules for targets named fcitx-addon-translation-handler-8

# Build rule for target.
fcitx-addon-translation-handler-8: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fcitx-addon-translation-handler-8
.PHONY : fcitx-addon-translation-handler-8

# fast build rule for target.
fcitx-addon-translation-handler-8/fast:
	$(MAKE) -f CMakeFiles/fcitx-addon-translation-handler-8.dir/build.make CMakeFiles/fcitx-addon-translation-handler-8.dir/build
.PHONY : fcitx-addon-translation-handler-8/fast

#=============================================================================
# Target rules for targets named fcitx-addon-translation-handler-9

# Build rule for target.
fcitx-addon-translation-handler-9: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fcitx-addon-translation-handler-9
.PHONY : fcitx-addon-translation-handler-9

# fast build rule for target.
fcitx-addon-translation-handler-9/fast:
	$(MAKE) -f CMakeFiles/fcitx-addon-translation-handler-9.dir/build.make CMakeFiles/fcitx-addon-translation-handler-9.dir/build
.PHONY : fcitx-addon-translation-handler-9/fast

#=============================================================================
# Target rules for targets named fcitx-extract-traslation.dependency

# Build rule for target.
fcitx-extract-traslation.dependency: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fcitx-extract-traslation.dependency
.PHONY : fcitx-extract-traslation.dependency

# fast build rule for target.
fcitx-extract-traslation.dependency/fast:
	$(MAKE) -f CMakeFiles/fcitx-extract-traslation.dependency.dir/build.make CMakeFiles/fcitx-extract-traslation.dependency.dir/build
.PHONY : fcitx-extract-traslation.dependency/fast

#=============================================================================
# Target rules for targets named fcitx-modules.target

# Build rule for target.
fcitx-modules.target: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fcitx-modules.target
.PHONY : fcitx-modules.target

# fast build rule for target.
fcitx-modules.target/fast:
	$(MAKE) -f CMakeFiles/fcitx-modules.target.dir/build.make CMakeFiles/fcitx-modules.target.dir/build
.PHONY : fcitx-modules.target/fast

#=============================================================================
# Target rules for targets named fcitx-parse-pos.dependency

# Build rule for target.
fcitx-parse-pos.dependency: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fcitx-parse-pos.dependency
.PHONY : fcitx-parse-pos.dependency

# fast build rule for target.
fcitx-parse-pos.dependency/fast:
	$(MAKE) -f CMakeFiles/fcitx-parse-pos.dependency.dir/build.make CMakeFiles/fcitx-parse-pos.dependency.dir/build
.PHONY : fcitx-parse-pos.dependency/fast

#=============================================================================
# Target rules for targets named fcitx-scan-addons.target

# Build rule for target.
fcitx-scan-addons.target: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fcitx-scan-addons.target
.PHONY : fcitx-scan-addons.target

# fast build rule for target.
fcitx-scan-addons.target/fast:
	$(MAKE) -f CMakeFiles/fcitx-scan-addons.target.dir/build.make CMakeFiles/fcitx-scan-addons.target.dir/build
.PHONY : fcitx-scan-addons.target/fast

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) -f CMakeFiles/uninstall.dir/build.make CMakeFiles/uninstall.dir/build
.PHONY : uninstall/fast

#=============================================================================
# Target rules for targets named fcitx-compile-mo.target

# Build rule for target.
fcitx-compile-mo.target: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fcitx-compile-mo.target
.PHONY : fcitx-compile-mo.target

# fast build rule for target.
fcitx-compile-mo.target/fast:
	$(MAKE) -f po/CMakeFiles/fcitx-compile-mo.target.dir/build.make po/CMakeFiles/fcitx-compile-mo.target.dir/build
.PHONY : fcitx-compile-mo.target/fast

#=============================================================================
# Target rules for targets named fcitx-parse-pos.target

# Build rule for target.
fcitx-parse-pos.target: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fcitx-parse-pos.target
.PHONY : fcitx-parse-pos.target

# fast build rule for target.
fcitx-parse-pos.target/fast:
	$(MAKE) -f po/CMakeFiles/fcitx-parse-pos.target.dir/build.make po/CMakeFiles/fcitx-parse-pos.target.dir/build
.PHONY : fcitx-parse-pos.target/fast

#=============================================================================
# Target rules for targets named fcitx-translate-pot.target

# Build rule for target.
fcitx-translate-pot.target: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fcitx-translate-pot.target
.PHONY : fcitx-translate-pot.target

# fast build rule for target.
fcitx-translate-pot.target/fast:
	$(MAKE) -f po/CMakeFiles/fcitx-translate-pot.target.dir/build.make po/CMakeFiles/fcitx-translate-pot.target.dir/build
.PHONY : fcitx-translate-pot.target/fast

#=============================================================================
# Target rules for targets named pot

# Build rule for target.
pot: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pot
.PHONY : pot

# fast build rule for target.
pot/fast:
	$(MAKE) -f po/CMakeFiles/pot.dir/build.make po/CMakeFiles/pot.dir/build
.PHONY : pot/fast

#=============================================================================
# Target rules for targets named fcitx-addon-fcitx-skk--addon--conf-1

# Build rule for target.
fcitx-addon-fcitx-skk--addon--conf-1: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fcitx-addon-fcitx-skk--addon--conf-1
.PHONY : fcitx-addon-fcitx-skk--addon--conf-1

# fast build rule for target.
fcitx-addon-fcitx-skk--addon--conf-1/fast:
	$(MAKE) -f src/CMakeFiles/fcitx-addon-fcitx-skk--addon--conf-1.dir/build.make src/CMakeFiles/fcitx-addon-fcitx-skk--addon--conf-1.dir/build
.PHONY : fcitx-addon-fcitx-skk--addon--conf-1/fast

#=============================================================================
# Target rules for targets named fcitx-addon-fcitx-skk--addon--conf-2

# Build rule for target.
fcitx-addon-fcitx-skk--addon--conf-2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fcitx-addon-fcitx-skk--addon--conf-2
.PHONY : fcitx-addon-fcitx-skk--addon--conf-2

# fast build rule for target.
fcitx-addon-fcitx-skk--addon--conf-2/fast:
	$(MAKE) -f src/CMakeFiles/fcitx-addon-fcitx-skk--addon--conf-2.dir/build.make src/CMakeFiles/fcitx-addon-fcitx-skk--addon--conf-2.dir/build
.PHONY : fcitx-addon-fcitx-skk--addon--conf-2/fast

#=============================================================================
# Target rules for targets named fcitx-addon-fcitx-skk--addon--desc-1

# Build rule for target.
fcitx-addon-fcitx-skk--addon--desc-1: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fcitx-addon-fcitx-skk--addon--desc-1
.PHONY : fcitx-addon-fcitx-skk--addon--desc-1

# fast build rule for target.
fcitx-addon-fcitx-skk--addon--desc-1/fast:
	$(MAKE) -f src/CMakeFiles/fcitx-addon-fcitx-skk--addon--desc-1.dir/build.make src/CMakeFiles/fcitx-addon-fcitx-skk--addon--desc-1.dir/build
.PHONY : fcitx-addon-fcitx-skk--addon--desc-1/fast

#=============================================================================
# Target rules for targets named fcitx-addon-fcitx-skk--headers-1

# Build rule for target.
fcitx-addon-fcitx-skk--headers-1: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fcitx-addon-fcitx-skk--headers-1
.PHONY : fcitx-addon-fcitx-skk--headers-1

# fast build rule for target.
fcitx-addon-fcitx-skk--headers-1/fast:
	$(MAKE) -f src/CMakeFiles/fcitx-addon-fcitx-skk--headers-1.dir/build.make src/CMakeFiles/fcitx-addon-fcitx-skk--headers-1.dir/build
.PHONY : fcitx-addon-fcitx-skk--headers-1/fast

#=============================================================================
# Target rules for targets named fcitx-skk

# Build rule for target.
fcitx-skk: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fcitx-skk
.PHONY : fcitx-skk

# fast build rule for target.
fcitx-skk/fast:
	$(MAKE) -f src/CMakeFiles/fcitx-skk.dir/build.make src/CMakeFiles/fcitx-skk.dir/build
.PHONY : fcitx-skk/fast

# Manual pre-install relink rule for target.
fcitx-skk/preinstall:
	$(MAKE) -f src/CMakeFiles/fcitx-skk.dir/build.make src/CMakeFiles/fcitx-skk.dir/preinstall
.PHONY : fcitx-skk/preinstall

#=============================================================================
# Target rules for targets named fcitx-skk--addon

# Build rule for target.
fcitx-skk--addon: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fcitx-skk--addon
.PHONY : fcitx-skk--addon

# fast build rule for target.
fcitx-skk--addon/fast:
	$(MAKE) -f src/CMakeFiles/fcitx-skk--addon.dir/build.make src/CMakeFiles/fcitx-skk--addon.dir/build
.PHONY : fcitx-skk--addon/fast

#=============================================================================
# Target rules for targets named fcitx-skk-config

# Build rule for target.
fcitx-skk-config: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fcitx-skk-config
.PHONY : fcitx-skk-config

# fast build rule for target.
fcitx-skk-config/fast:
	$(MAKE) -f gui/CMakeFiles/fcitx-skk-config.dir/build.make gui/CMakeFiles/fcitx-skk-config.dir/build
.PHONY : fcitx-skk-config/fast

# Manual pre-install relink rule for target.
fcitx-skk-config/preinstall:
	$(MAKE) -f gui/CMakeFiles/fcitx-skk-config.dir/build.make gui/CMakeFiles/fcitx-skk-config.dir/preinstall
.PHONY : fcitx-skk-config/preinstall

#=============================================================================
# Target rules for targets named fcitx-skk-config_automoc

# Build rule for target.
fcitx-skk-config_automoc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fcitx-skk-config_automoc
.PHONY : fcitx-skk-config_automoc

# fast build rule for target.
fcitx-skk-config_automoc/fast:
	$(MAKE) -f gui/CMakeFiles/fcitx-skk-config_automoc.dir/build.make gui/CMakeFiles/fcitx-skk-config_automoc.dir/build
.PHONY : fcitx-skk-config_automoc/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... fcitx-addon-translation-handler-1"
	@echo "... fcitx-addon-translation-handler-10"
	@echo "... fcitx-addon-translation-handler-11"
	@echo "... fcitx-addon-translation-handler-12"
	@echo "... fcitx-addon-translation-handler-2"
	@echo "... fcitx-addon-translation-handler-3"
	@echo "... fcitx-addon-translation-handler-4"
	@echo "... fcitx-addon-translation-handler-5"
	@echo "... fcitx-addon-translation-handler-6"
	@echo "... fcitx-addon-translation-handler-7"
	@echo "... fcitx-addon-translation-handler-8"
	@echo "... fcitx-addon-translation-handler-9"
	@echo "... fcitx-extract-traslation.dependency"
	@echo "... fcitx-modules.target"
	@echo "... fcitx-parse-pos.dependency"
	@echo "... fcitx-scan-addons.target"
	@echo "... install"
	@echo "... install/local"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... uninstall"
	@echo "... fcitx-compile-mo.target"
	@echo "... fcitx-parse-pos.target"
	@echo "... fcitx-translate-pot.target"
	@echo "... pot"
	@echo "... fcitx-addon-fcitx-skk--addon--conf-1"
	@echo "... fcitx-addon-fcitx-skk--addon--conf-2"
	@echo "... fcitx-addon-fcitx-skk--addon--desc-1"
	@echo "... fcitx-addon-fcitx-skk--headers-1"
	@echo "... fcitx-skk"
	@echo "... fcitx-skk--addon"
	@echo "... fcitx-skk-config"
	@echo "... fcitx-skk-config_automoc"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

